version: '3.6'
services:
  efs-eureka-server:
    build: ./../../efs-eureka-server
    container_name: "efs-eureka-server"
    ports:
      - 8761:8761
  efs-api-gateway-zuul:
    build: ./../../efs-api-gateway-zuul
    container_name: "efs-api-gateway-zuul"
    ports:
      - 8765:8765
    environment:
      eureka.client.serviceUrl.defaultZone: http://efs-eureka-server:8761/eureka/
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
  kafka:
    image: confluentinc/cp-kafka:5.2.1
    ports:
    - "9092:9092"
    depends_on:
    - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  mongo:
    image: mongo
    restart: always
    container_name: "efs-database"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example